version: '3.8'

networks:
  picpay-network:
    driver: bridge

services:
  db:
    build: ./services/database
    container_name: picpay-database
    networks:
      - picpay-network
    ports:
      - '5432:5432'
  picpay-api:
    build: ./services/picpay-api
    container_name: picpay-api
    depends_on:
      - db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/picpay_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      KAFKA_BROKER_CONNECT: "kafka:9094"
    networks:
      - picpay-network
    ports:
      - '8080:8080'
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - picpay-network
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://kafka:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
